#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vPlanDBApi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ElefantStudio_Dev")]
	public partial class vPlanLinqSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertOrganisation(Organisation instance);
    partial void UpdateOrganisation(Organisation instance);
    partial void DeleteOrganisation(Organisation instance);
    partial void InsertArbetsplat(Arbetsplat instance);
    partial void UpdateArbetsplat(Arbetsplat instance);
    partial void DeleteArbetsplat(Arbetsplat instance);
    #endregion
		
		public vPlanLinqSQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ElefantStudio_DevConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public vPlanLinqSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vPlanLinqSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vPlanLinqSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vPlanLinqSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Organisation> Organisations
		{
			get
			{
				return this.GetTable<Organisation>();
			}
		}
		
		public System.Data.Linq.Table<Arbetsplat> Arbetsplats
		{
			get
			{
				return this.GetTable<Arbetsplat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _UserName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _EmailAdress;
		
		private System.Data.Linq.Binary _Salt;
		
		private System.Data.Linq.Binary _Password;
		
		private System.Nullable<System.DateTime> _LastOn;
		
		private System.Nullable<System.DateTime> _createdOn;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _employProcent;
		
		private string _employForm;
		
		private System.Guid _arbetsplats_id;
		
		private EntitySet<Arbetsplat> _Arbetsplats;
		
		private EntitySet<Arbetsplat> _Arbetsplats1;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailAdressChanging(string value);
    partial void OnEmailAdressChanged();
    partial void OnSaltChanging(System.Data.Linq.Binary value);
    partial void OnSaltChanged();
    partial void OnPasswordChanging(System.Data.Linq.Binary value);
    partial void OnPasswordChanged();
    partial void OnLastOnChanging(System.Nullable<System.DateTime> value);
    partial void OnLastOnChanged();
    partial void OncreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedOnChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnemployProcentChanging(System.Nullable<int> value);
    partial void OnemployProcentChanged();
    partial void OnemployFormChanging(string value);
    partial void OnemployFormChanged();
    partial void Onarbetsplats_idChanging(System.Guid value);
    partial void Onarbetsplats_idChanged();
    #endregion
		
		public User()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAdress", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string EmailAdress
		{
			get
			{
				return this._EmailAdress;
			}
			set
			{
				if ((this._EmailAdress != value))
				{
					this.OnEmailAdressChanging(value);
					this.SendPropertyChanging();
					this._EmailAdress = value;
					this.SendPropertyChanged("EmailAdress");
					this.OnEmailAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salt", DbType="VarBinary(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Data.Linq.Binary Salt
		{
			get
			{
				return this._Salt;
			}
			set
			{
				if ((this._Salt != value))
				{
					this.OnSaltChanging(value);
					this.SendPropertyChanging();
					this._Salt = value;
					this.SendPropertyChanged("Salt");
					this.OnSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Binary(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Data.Linq.Binary Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastOn", DbType="Date")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> LastOn
		{
			get
			{
				return this._LastOn;
			}
			set
			{
				if ((this._LastOn != value))
				{
					this.OnLastOnChanging(value);
					this.SendPropertyChanging();
					this._LastOn = value;
					this.SendPropertyChanged("LastOn");
					this.OnLastOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdOn", DbType="Date")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<System.DateTime> createdOn
		{
			get
			{
				return this._createdOn;
			}
			set
			{
				if ((this._createdOn != value))
				{
					this.OncreatedOnChanging(value);
					this.SendPropertyChanging();
					this._createdOn = value;
					this.SendPropertyChanged("createdOn");
					this.OncreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employProcent", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> employProcent
		{
			get
			{
				return this._employProcent;
			}
			set
			{
				if ((this._employProcent != value))
				{
					this.OnemployProcentChanging(value);
					this.SendPropertyChanging();
					this._employProcent = value;
					this.SendPropertyChanged("employProcent");
					this.OnemployProcentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employForm", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string employForm
		{
			get
			{
				return this._employForm;
			}
			set
			{
				if ((this._employForm != value))
				{
					this.OnemployFormChanging(value);
					this.SendPropertyChanging();
					this._employForm = value;
					this.SendPropertyChanged("employForm");
					this.OnemployFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arbetsplats_id", AutoSync=AutoSync.Always, DbType="UniqueIdentifier NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Guid arbetsplats_id
		{
			get
			{
				return this._arbetsplats_id;
			}
			set
			{
				if ((this._arbetsplats_id != value))
				{
					this.Onarbetsplats_idChanging(value);
					this.SendPropertyChanging();
					this._arbetsplats_id = value;
					this.SendPropertyChanged("arbetsplats_id");
					this.Onarbetsplats_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Arbetsplat", Storage="_Arbetsplats", ThisKey="arbetsplats_id", OtherKey="Id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14, EmitDefaultValue=false)]
		public EntitySet<Arbetsplat> Arbetsplats
		{
			get
			{
				if ((this.serializing 
							&& (this._Arbetsplats.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Arbetsplats;
			}
			set
			{
				this._Arbetsplats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Arbetsplat1", Storage="_Arbetsplats1", ThisKey="Id", OtherKey="personal_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15, EmitDefaultValue=false)]
		public EntitySet<Arbetsplat> Arbetsplats1
		{
			get
			{
				if ((this.serializing 
							&& (this._Arbetsplats1.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Arbetsplats1;
			}
			set
			{
				this._Arbetsplats1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Arbetsplats(Arbetsplat entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Arbetsplats(Arbetsplat entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Arbetsplats1(Arbetsplat entity)
		{
			this.SendPropertyChanging();
			entity.User1 = this;
		}
		
		private void detach_Arbetsplats1(Arbetsplat entity)
		{
			this.SendPropertyChanging();
			entity.User1 = null;
		}
		
		private void Initialize()
		{
			this._Arbetsplats = new EntitySet<Arbetsplat>(new Action<Arbetsplat>(this.attach_Arbetsplats), new Action<Arbetsplat>(this.detach_Arbetsplats));
			this._Arbetsplats1 = new EntitySet<Arbetsplat>(new Action<Arbetsplat>(this.attach_Arbetsplats1), new Action<Arbetsplat>(this.detach_Arbetsplats1));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Organisation")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Organisation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Namn;
		
		private string _Ansvarig;
		
		private string _Telefonummer;
		
		private System.Guid _arbetsplatser_id;
		
		private EntityRef<Arbetsplat> _Arbetsplat;
		
		private EntityRef<Arbetsplat> _Arbetsplat1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNamnChanging(string value);
    partial void OnNamnChanged();
    partial void OnAnsvarigChanging(string value);
    partial void OnAnsvarigChanged();
    partial void OnTelefonummerChanging(string value);
    partial void OnTelefonummerChanged();
    partial void Onarbetsplatser_idChanging(System.Guid value);
    partial void Onarbetsplatser_idChanged();
    #endregion
		
		public Organisation()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._Arbetsplat1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namn", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Namn
		{
			get
			{
				return this._Namn;
			}
			set
			{
				if ((this._Namn != value))
				{
					this.OnNamnChanging(value);
					this.SendPropertyChanging();
					this._Namn = value;
					this.SendPropertyChanged("Namn");
					this.OnNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ansvarig", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Ansvarig
		{
			get
			{
				return this._Ansvarig;
			}
			set
			{
				if ((this._Ansvarig != value))
				{
					this.OnAnsvarigChanging(value);
					this.SendPropertyChanging();
					this._Ansvarig = value;
					this.SendPropertyChanged("Ansvarig");
					this.OnAnsvarigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonummer", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Telefonummer
		{
			get
			{
				return this._Telefonummer;
			}
			set
			{
				if ((this._Telefonummer != value))
				{
					this.OnTelefonummerChanging(value);
					this.SendPropertyChanging();
					this._Telefonummer = value;
					this.SendPropertyChanged("Telefonummer");
					this.OnTelefonummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arbetsplatser_id", AutoSync=AutoSync.Always)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Guid arbetsplatser_id
		{
			get
			{
				return this._arbetsplatser_id;
			}
			set
			{
				if ((this._arbetsplatser_id != value))
				{
					if (this._Arbetsplat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onarbetsplatser_idChanging(value);
					this.SendPropertyChanging();
					this._arbetsplatser_id = value;
					this.SendPropertyChanged("arbetsplatser_id");
					this.Onarbetsplatser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Arbetsplat_Organisation", Storage="_Arbetsplat", ThisKey="arbetsplatser_id", OtherKey="Id", IsForeignKey=true)]
		public Arbetsplat Arbetsplat
		{
			get
			{
				return this._Arbetsplat.Entity;
			}
			set
			{
				Arbetsplat previousValue = this._Arbetsplat.Entity;
				if (((previousValue != value) 
							|| (this._Arbetsplat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Arbetsplat.Entity = null;
						previousValue.Organisations.Remove(this);
					}
					this._Arbetsplat.Entity = value;
					if ((value != null))
					{
						value.Organisations.Add(this);
						this._arbetsplatser_id = value.Id;
					}
					else
					{
						this._arbetsplatser_id = default(System.Guid);
					}
					this.SendPropertyChanged("Arbetsplat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Arbetsplat_Organisation1", Storage="_Arbetsplat1", ThisKey="Id", OtherKey="organisation_id", IsForeignKey=true)]
		public Arbetsplat Arbetsplat1
		{
			get
			{
				return this._Arbetsplat1.Entity;
			}
			set
			{
				Arbetsplat previousValue = this._Arbetsplat1.Entity;
				if (((previousValue != value) 
							|| (this._Arbetsplat1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Arbetsplat1.Entity = null;
						previousValue.Organisations1.Remove(this);
					}
					this._Arbetsplat1.Entity = value;
					if ((value != null))
					{
						value.Organisations1.Add(this);
						this._Id = value.organisation_id;
					}
					else
					{
						this._Id = default(System.Guid);
					}
					this.SendPropertyChanged("Arbetsplat1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Arbetsplat = default(EntityRef<Arbetsplat>);
			this._Arbetsplat1 = default(EntityRef<Arbetsplat>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Arbetsplats")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Arbetsplat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Namn;
		
		private string _Ansvarig;
		
		private string _Adress;
		
		private string _Postnummer;
		
		private string _Stad;
		
		private string _Telefonummer;
		
		private string _Direktnummer;
		
		private System.Guid _organisation_id;
		
		private System.Nullable<System.Guid> _personal_id;
		
		private EntitySet<Organisation> _Organisations;
		
		private EntitySet<Organisation> _Organisations1;
		
		private EntityRef<User> _User;
		
		private EntityRef<User> _User1;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNamnChanging(string value);
    partial void OnNamnChanged();
    partial void OnAnsvarigChanging(string value);
    partial void OnAnsvarigChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnPostnummerChanging(string value);
    partial void OnPostnummerChanged();
    partial void OnStadChanging(string value);
    partial void OnStadChanged();
    partial void OnTelefonummerChanging(string value);
    partial void OnTelefonummerChanged();
    partial void OnDirektnummerChanging(string value);
    partial void OnDirektnummerChanged();
    partial void Onorganisation_idChanging(System.Guid value);
    partial void Onorganisation_idChanged();
    partial void Onpersonal_idChanging(System.Nullable<System.Guid> value);
    partial void Onpersonal_idChanged();
    #endregion
		
		public Arbetsplat()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namn", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Namn
		{
			get
			{
				return this._Namn;
			}
			set
			{
				if ((this._Namn != value))
				{
					this.OnNamnChanging(value);
					this.SendPropertyChanging();
					this._Namn = value;
					this.SendPropertyChanged("Namn");
					this.OnNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ansvarig", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Ansvarig
		{
			get
			{
				return this._Ansvarig;
			}
			set
			{
				if ((this._Ansvarig != value))
				{
					this.OnAnsvarigChanging(value);
					this.SendPropertyChanging();
					this._Ansvarig = value;
					this.SendPropertyChanged("Ansvarig");
					this.OnAnsvarigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnummer", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Postnummer
		{
			get
			{
				return this._Postnummer;
			}
			set
			{
				if ((this._Postnummer != value))
				{
					this.OnPostnummerChanging(value);
					this.SendPropertyChanging();
					this._Postnummer = value;
					this.SendPropertyChanged("Postnummer");
					this.OnPostnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stad", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Stad
		{
			get
			{
				return this._Stad;
			}
			set
			{
				if ((this._Stad != value))
				{
					this.OnStadChanging(value);
					this.SendPropertyChanging();
					this._Stad = value;
					this.SendPropertyChanged("Stad");
					this.OnStadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonummer", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Telefonummer
		{
			get
			{
				return this._Telefonummer;
			}
			set
			{
				if ((this._Telefonummer != value))
				{
					this.OnTelefonummerChanging(value);
					this.SendPropertyChanging();
					this._Telefonummer = value;
					this.SendPropertyChanged("Telefonummer");
					this.OnTelefonummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direktnummer", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Direktnummer
		{
			get
			{
				return this._Direktnummer;
			}
			set
			{
				if ((this._Direktnummer != value))
				{
					this.OnDirektnummerChanging(value);
					this.SendPropertyChanging();
					this._Direktnummer = value;
					this.SendPropertyChanged("Direktnummer");
					this.OnDirektnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organisation_id", AutoSync=AutoSync.Always, DbType="UniqueIdentifier NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Guid organisation_id
		{
			get
			{
				return this._organisation_id;
			}
			set
			{
				if ((this._organisation_id != value))
				{
					this.Onorganisation_idChanging(value);
					this.SendPropertyChanging();
					this._organisation_id = value;
					this.SendPropertyChanged("organisation_id");
					this.Onorganisation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personal_id", AutoSync=AutoSync.Always)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<System.Guid> personal_id
		{
			get
			{
				return this._personal_id;
			}
			set
			{
				if ((this._personal_id != value))
				{
					if (this._User1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpersonal_idChanging(value);
					this.SendPropertyChanging();
					this._personal_id = value;
					this.SendPropertyChanged("personal_id");
					this.Onpersonal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Arbetsplat_Organisation", Storage="_Organisations", ThisKey="Id", OtherKey="arbetsplatser_id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11, EmitDefaultValue=false)]
		public EntitySet<Organisation> Organisations
		{
			get
			{
				if ((this.serializing 
							&& (this._Organisations.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Organisations;
			}
			set
			{
				this._Organisations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Arbetsplat_Organisation1", Storage="_Organisations1", ThisKey="organisation_id", OtherKey="Id")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12, EmitDefaultValue=false)]
		public EntitySet<Organisation> Organisations1
		{
			get
			{
				if ((this.serializing 
							&& (this._Organisations1.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Organisations1;
			}
			set
			{
				this._Organisations1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Arbetsplat", Storage="_User", ThisKey="Id", OtherKey="arbetsplats_id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Arbetsplats.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Arbetsplats.Add(this);
						this._Id = value.arbetsplats_id;
					}
					else
					{
						this._Id = default(System.Guid);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Arbetsplat1", Storage="_User1", ThisKey="personal_id", OtherKey="Id", IsForeignKey=true)]
		public User User1
		{
			get
			{
				return this._User1.Entity;
			}
			set
			{
				User previousValue = this._User1.Entity;
				if (((previousValue != value) 
							|| (this._User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User1.Entity = null;
						previousValue.Arbetsplats1.Remove(this);
					}
					this._User1.Entity = value;
					if ((value != null))
					{
						value.Arbetsplats1.Add(this);
						this._personal_id = value.Id;
					}
					else
					{
						this._personal_id = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Organisations(Organisation entity)
		{
			this.SendPropertyChanging();
			entity.Arbetsplat = this;
		}
		
		private void detach_Organisations(Organisation entity)
		{
			this.SendPropertyChanging();
			entity.Arbetsplat = null;
		}
		
		private void attach_Organisations1(Organisation entity)
		{
			this.SendPropertyChanging();
			entity.Arbetsplat1 = this;
		}
		
		private void detach_Organisations1(Organisation entity)
		{
			this.SendPropertyChanging();
			entity.Arbetsplat1 = null;
		}
		
		private void Initialize()
		{
			this._Organisations = new EntitySet<Organisation>(new Action<Organisation>(this.attach_Organisations), new Action<Organisation>(this.detach_Organisations));
			this._Organisations1 = new EntitySet<Organisation>(new Action<Organisation>(this.attach_Organisations1), new Action<Organisation>(this.detach_Organisations1));
			this._User = default(EntityRef<User>);
			this._User1 = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
}
#pragma warning restore 1591
